version = 1
SPDX-PackageName = "chatgpt-asr"
SPDX-PackageSupplier = "Maryam Naderi <maryam.naderi@idiap.ch>"
SPDX-PackageDownloadLocation = "https://gitlab.idiap.ch/mnaderi/chat-gpt-asr.git"

[[annotations]]
path = [".gitignore", "README.md", "requirements.txt", "setup.py", "THIRDPARTY.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2023 Idiap Research Institute <contact@idiap.ch>"
SPDX-License-Identifier = "LicenseRef-chatgpt-asr"

[[annotations]]
path = ["scripts/**.py", "scripts/**/**.py", "src/**/*.py"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2023 Idiap Research Institute <contact@idiap.ch>"
SPDX-License-Identifier = "LicenseRef-chatgpt-asr"

[[annotations]]
path = "**/**.ipynb"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2023 Idiap Research Institute <contact@idiap.ch>"
SPDX-License-Identifier = "LicenseRef-chatgpt-asr"

[[annotations]]
path = "**/**.py"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright © 2023 Idiap Research Institute <contact@idiap.ch>"
SPDX-License-Identifier = "LicenseRef-chatgpt-asr"
